// react/class-based/bundled-player/src/bitmovinPlayer.js
import React from 'react';
import {Player} from 'bitmovin-player';
import {UIFactory} from 'bitmovin-player/bitmovinplayer-ui';
import 'bitmovin-player/bitmovinplayer-ui.css';

class BitmovinPlayer extends React.Component {

  state = {
    player: null,
  };

  playerConfig = {
    key: 'YOUR KEY HERE'
  };

  playerSource = {
    dash: 'https://bitdash-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd',
    hls: 'https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8',
    poster: 'https://bitdash-a.akamaihd.net/content/MI201109210084_1/poster.jpg'
  };

  constructor(props) {
    super(props);
    this.playerDiv = React.createRef();
  }

  componentDidMount() {
    this.setupPlayer();
  }

  componentWillUnmount() {
    this.destroyPlayer();
  }

  setupPlayer() {
    const player = new Player(this.playerDiv.current, this.playerConfig);
    UIFactory.buildDefaultUI(player);
    player.load(this.playerSource).then(() => {
      this.setState({
        ...this.state,
        player
      });
      console.log('Successfully loaded source');
    }, () => {
      console.log('Error while loading source');
    });
  }

  destroyPlayer() {
    if (this.state.player != null) {
      this.state.player.destroy();
      this.setState({
        ...this.state,
        player: null
      });
    }
  }

  render() {
    return <div id='player' ref={this.playerDiv}/>;
  }
}

export default BitmovinPlayer;

// angular/src/app/bitmovin-player/bitmovin-player.component.ts
import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { Player } from 'bitmovin-player';
import { UIFactory } from 'bitmovin-player/bitmovinplayer-ui';

@Component({
  selector: 'app-bitmovin-player',
  templateUrl: './bitmovin-player.component.html',
  styleUrls: ['./bitmovin-player.component.css']
})
export class BitmovinPlayerComponent implements AfterViewInit {
  @ViewChild('player') playerElement;

  player; playerConfig;

  constructor() {
    this.playerConfig = {
      key: 'YOUR KEY HERE',
      ui: false
    };
  }

  ngAfterViewInit(): void {
     const playerSource = {
      dash: 'https://bitdash-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd',
      hls: 'https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8',
      poster: 'https://bitdash-a.akamaihd.net/content/MI201109210084_1/poster.jpg'
    };
     this.player = new Player(this.playerElement.nativeElement, this.playerConfig);
     UIFactory.buildDefaultUI(this.player);
     this.player.load(playerSource).then(() => {
      console.log('Successfully loaded source');
    }, () => {
      console.log('Error while loading source');
    });
  }

  ngDestroy(): void{
    if (this.player) {
      this.player.destroy();
    }

  }

}

<div #player id='player'></div>
